
data:
  use_augmentations: yes
  root: /home/paulw/data/mnist
  download: true
  noise_rate: 0.95
  seed: 0
  batch_size: 32

model:
  type: cnn

loss:
  name: 'cross_entropy'

opt_config:
  final_forget_rate: 0.95
  final_forget_rate_epoch: 20
  lr: 1e-4

mode: 'coteaching'

trainer:
  max_epochs: 50

logger:
  type: wandb
  name: null
  save_dir: null
  project: coteaching