
defaults: 
  - _self_ 
  - data: default

model:
  type: our_cnn

loss:
  name: 'cross_entropy'

opt_config:
  final_forget_rate: 0
  final_forget_rate_epoch: 10
  lr: 1e-2

mode: 'coteaching'

trainer:
  min_epochs:
  accelerator: gpu
  gpus: 1
  #limit_train_batches: 0.1
  #overfit_batches: 

callbacks:
  #early_stopping:
  #  patience: 3 
  #  monitor: val/accuracy
  #  mode: max 
  log_training_sample_images: yes
  log_test_pred_samples: yes

logger:
  type: wandb
  name: null
  save_dir: null
  project: coteaching